version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db_apartaments
    volumes:
      - ./src:/usr/app/src

  db_apartaments:
    container_name: db_apartaments
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    image: postgres:14.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: